development:
  adapter: mysql2
  encoding: utf8
  database: avc_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: avc_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: avc_production
  username: root
  password:
  socket: /tmp/mysql.sock

